version: "3.9"

services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=env:postgres
      - POSTGRES_USER=env:postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/simple-irc
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
