# Generated by Django 4.1 on 2022-08-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="nickname",
            new_name="username",
        ),
    ]
