# Generated by Django 4.1 on 2022-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thread", "0002_thread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
