# Generated by Django 4.1 on 2022-08-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network_name", models.CharField(max_length=255)),
                ("hostname", models.CharField(max_length=63)),
                ("port", models.IntegerField(default=6667)),
            ],
        ),
    ]
